[tool.pyright]
pythonVersion = "3.10"
pythonPlatform = "Linux"
exclude = ["**/{.bzr,.direnv,.eggs,.git,.pytest_cache,.pytype,.ruff_cache,.venv,.vscode,__pypackages__,_build,buck-out,build,dist,node_modules,site-packages,venv}"]
venvPath = "."
venv = ".venv"
typeCheckingMode = "basic"

[tool.black]
line-length = 79

[tool.isort]
known_third_party = ["fastapi"]
known_first_party = ["app"]

