section_breakdown_task:
    description: "Break down the resume into sections and identify the most important sections."
    expected_output: "A list of sections and their importance ranking. {resume_contents}"
    agent: "resume_structure_analyst"

overall_score_evaluation:
    description: "Assess the overall quality of the resume"
    expected_output: "A score between 0 and 100 indicating the overall quality of the resume. {resume_contents}"
    agent: "resume_quality_evaluator"

consistency_score_evaluation:
  description: "Assess the consistency of the resume"
  expected_output: "A score between 0 and 100 indicating the consistency of the resume. {resume_contents}"
  agent: "resume_quality_evaluator"

formatting_score_evaluation:
  description: "Assess the formatting of the resume"
  expected_output: "A score between 0 and 100 indicating the formatting of the resume. {resume_contents}"
  agent: "resume_quality_evaluator"

grammar_score_evaluation:
  description: "Assess the grammar of the resume"
  expected_output: "A score between 0 and 100 indicating the grammar of the resume. {resume_contents}"
  agent: "resume_quality_evaluator"

resume_summary_evaluation:
    description: "Assess clarity and impact of the summary"
    expected_output: "A list of issues, including unclear summary, weak summary, and inadequate summary. {resume_contents}"
    agent: "summary_experience_assessor"

resume_experience_assessment:
    description: "Find weak or vague descriptions in experience"
    expected_output: "A list of issues, including weak experience descriptions, vague experience descriptions, and missing experience details. {resume_contents}"
    agent: "summary_experience_assessor"

resume_education_check:
    description: "Detect unclear or inconsistent education details"
    expected_output: "A list of issues, including unclear education details, inconsistent education details, and missing education details. {resume_contents}"
    agent: "education_skills_verifier"

resume_skills_assessment:
    description: "Identify missing or outdated skills"
    expected_output: "A list of issues, including missing skills, outdated skills, and irrelevant skills. {resume_contents}"
    agent: "education_skills_verifier"

resume_project_reviewer:
    description: "Highlight unclear project descriptions"
    expected_output: "A list of issues, including unclear project descriptions, missing project details, and weak project descriptions. {resume_contents}"
    agent: "project_achievement_reviewer"

