services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    ports:
      - "${TRAEFIK_HTTP_PORT}:80"
      - "${TRAEFIK_DASHBOARD_PORT}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik/static.yml:/traefik.yml:ro
      - ./config/traefik/dynamic.yml:/dynamic.yml:ro
    networks:
      - main-network

  crewai-server:
    image: crewai-server:latest
    restart: unless-stopped
    environment:
      SHARED_FOLDER: "${SHARED_FOLDER}"
    env_file:
      - ./envs/.env.crewai-server
    user: "1000:1000"
    volumes:
      - resume-opt-shared:/home/appuser/shared
    networks:
      - main-network
  
  fastapi-server:
    image: fastapi-server:latest
    restart: unless-stopped
    environment:
      SHARED_FOLDER: "${SHARED_FOLDER}"
      API_CONFIG_CREWAI_FASTAPI_URL: "${API_CONFIG_CREWAI_FASTAPI_URL}"
    user: "1000:1000"
    volumes:
      - fastapi-shared:/home/appuser/shared
    depends_on:
      - traefik
      - crewai-server
    networks:
      - main-network

networks:
  main-network:
    driver: bridge

volumes:
  fastapi-shared:
    driver: local
    driver_opts:
      type: none
      device: "./data/main/shared"
      o: bind
  resume-opt-shared:
    driver: local
    driver_opts:
      type: none
      device: "./data/main/shared"
      o: bind
