section_breakdown_task:
    description: "Break down the resume into sections and identify the most important sections."
    expected_output: "A list of sections and their importance ranking. Read the input schema carefully. Specially the complex ones like for dates and contact info. {resume_contents}"
    agent: "resume_structure_analyst"

resume_experience_assessment:
    description: "Find weak or vague descriptions in experience"
    expected_output: "A list of issues, including weak experience descriptions, vague experience descriptions, and missing experience details. {contents}"
    agent: "summary_experience_assessor"

resume_education_check:
    description: "Detect unclear or inconsistent education details"
    expected_output: "A list of issues, including unclear education details, inconsistent education details, and missing education details. {contents}"
    agent: "education_skills_verifier"

resume_skills_assessment:
    description: "Identify missing or outdated skills"
    expected_output: "A list of issues, including missing skills, outdated skills, and irrelevant skills. {contents}"
    agent: "education_skills_verifier"

resume_project_reviewer:
    description: "Highlight unclear project descriptions"
    expected_output: "A list of issues, including unclear project descriptions, missing project details, and weak project descriptions. {contents}"
    agent: "project_achievement_reviewer"

