keyword_density_optimization:
  description: "Optimize the density of keywords in the resume by adjusting their frequency."
  expected_output: |
    Optimize the keyword density until it reaches the target density. Target density is specified below for each section:
    
    - **Header & Summary**: Ideal 3-4%  
    - **Skills Section**: Ideal 4-6%  
    - **Work Experience**: Ideal 2-3%  
    - **Education & Certifications**: Ideal 2-3%  
    - **Additional Sections (Projects, Awards, Volunteer Work)**: Ideal 2-3%
  agent: "keyword_density_optimizer"

resume_length_maintain:
  description: "Ensure the resume maintains its original length while incorporating optimized keywords."
  expected_output: "Integrate the keyword-optimized text into the resume without omitting any section or relevant information. Preserve the quality and structure of the resume. Return the resume in markdown format {resume_contents}"
  agent: "resume_length_maintainer"

